### DISCUSSION TITLE
Improve k8s configuration

### DISCUSSION THREAD

**Discussion by luoluoyuyu** [apache/streampipes#1799] [Dev] [answered]
## Purpose
Improve k8s configuration

## Program

1. Make the pods start in order, using the k8s 'Init Container'.

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.streampipes.ui.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.streampipes.ui.appName }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.streampipes.ui.appName }}
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
      restartPolicy: {{ .Values.restartPolicy }}
      initContainers:
      - name: init-wait-consul-couchdb-extensions-all-iiot
        image: alpine
        command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 consul 8500 && nc -zvw1 couchdb 5984 && nc -zvw1 extensions-all-iiot 8090 && exit 0 || sleep 3; done; exit 1"]
```

2. References the values in the 'value.yml' file.
```yml
extensions:
  iiot:
    appName: extensions-all-iiot
    port: 8090
    service:
      name: extensions-all-iiot
      labelsName: extensions-all-iiot
      port: 8090
```
```yml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.extensions.iiot.service.name }}
  labels:
    name: {{ .Values.extensions.iiot.service.labelsName }}
spec:
  selector:
    app: {{ .Values.extensions.iiot.appName }}
  ports:
    - name: main
      protocol: TCP
      port: {{ .Values.extensions.iiot.port }}
      targetPort: {{ .Values.extensions.iiot.service.port }}
```
