### DISCUSSION TITLE
when use docker-compose.full.yml  then  manifest unknown

### DISCUSSION THREAD

**Discussion by zcwleo** [apache/streampipes#1849] [Q&A]
when docker compose -f docker-compose.full.yml up -d

Error response from daemon: manifest for apachestreampipes/sources-vehicle-simulator:0.92.0 not found: manifest unknown: manifest unknown

**Comment by tenthe** [comment]
Hi @zcwleo,

thank you for the hint. This is an already known issue that will be fixed in the next release (see #1668).
For now, you need to manually edit the "docker-compose.full.yml" file and remove the "followint" part:

```
  sources-vehicle-simulator:
    image: "${SP_DOCKER_REGISTRY}/sources-vehicle-simulator:${SP_VERSION}"
    depends_on:
      - consul
      - kafka
    logging: *default-logging
    restart: unless-stopped
    networks:
      spnet:
```

I hope this explanation is helpful. If you have any further problems or questions, please feel free to contact us at any time.

Cheers,
Philipp
