### DISCUSSION TITLE
Env vars for docker set up?

### DISCUSSION THREAD

**Discussion by andrewzah** [apache/streampipes#2488] [Q&A]
The [docs](https://streampipes.apache.org/docs/try-installation/) link to a [docker-compose.yml](https://github.com/apache/streampipes/blob/dev/installer/compose/docker-compose.yml), but things seem to expect hardcoded dns names, such as `backend`. The [Environment Variables page](https://streampipes.apache.org/docs/deploy-environment-variables/) doesn't seem to mention them. How can I connect these services without hardcoded DNS?

```yaml
---

services:
  foo:
    image: docker.io/apachestreampipes/backend:0.93.0
    environment:
      SP_HTTP_SERVER_ADAPTER_ENDPOINT: bar:8090
    ports:
      - "8030"
      - "8090"

  bar:
    image: docker.io/apachestreampipes/extensions-all-jvm:0.93.0
    environment:
      SP_HTTP_SERVER_ADAPTER_ENDPOINT: bar:8090
    ports:
      - "8030"
      - "8090"

  ui:
    image: docker.io/apachestreampipes/ui:0.93.0
    ports:
      - "8088"

```

**Comment by dominikriemer** [comment]
Hi @andrewzah for extension services, you can provide the environment variable `SP_CORE_HOST` to link to the backend (you can also set `SP_CORE_SCHEME` in case the backend is running on HTTPS and `SP_CORE_PORT` to assign another port than the default port. The extension service itself can be any name since its IP is resolved at startup time, but this can be overriden by providing the `SP_HOST` and SP_PORT` variables.

For the reverse proxy configuration in the UI, you can change the default nginx configuration from https://github.com/apache/streampipes/blob/dev/ui/nginx_config/default.conf and add a volume mapping.

Hope this helps!

**Comment by andrewzah** [comment]
@dominikriemer `SP_CORE_HOST` doesn't seem to be working. The extension tries to register to itself (`172.20.0.4`) instead of `core` which is at `172.20.0.3`.
```
ext-1  | 2024-05-22T07:52:07.942Z  WARN   --- [           main] o.a.s.s.extensions.CoreRequestSubmitter  : Could not register service at core at url http://172.20.0.4:8030 Trying again in 3 seconds
```

```yaml
services:
  ui:
    image: apachestreampipes/ui:0.95.0-SNAPSHOT
    environment:
      SP_HTTP_SERVER_ADAPTER_ENDPOINT: 'ext:8090'
    ports:
      - "80:8088"

  core:
    image: docker.io/apachestreampipes/backend:0.93.0
    ports:
      - "8030"
      - "8090"
    environment:
      SP_INITIAL_ADMIN_EMAIL: 'admin@example.com'
      SP_INITIAL_ADMIN_PASSWORD: 'admin'
      SP_COUCHDB_HOST: couchdb
      SP_DEBUG: true

  ext:
    image: docker.io/apachestreampipes/extensions-all-jvm:0.93.0
    ports:
      - "8030"
      - "8090"
    environment:
      SP_DEBUG: true
      SP_COUCHDB_HOST: couchdb
      SP_CORE_HOST: core
```
