### ISSUE TITLE
Build GitHub workflow to deploy Python library to Pypi

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1230]
### Body

To deploy out Python library to pypi.org we need a dedicated GitHub workflow since we do not publish snapshot versions in the beginning. This workflow should only be triggered manually, which will be done during the release process. It only needs to build the wheel and publish the it to Pypi using `setup.py`.

- [x] build GitHub workflow
- [x] add PyPi credentials to GitHub @bossenti (available as `PYPI_TOKEN` )
- [x] update release process documentation in Confluence -> https://cwiki.apache.org/confluence/display/STREAMPIPES/Post-release+steps

We will test/run this during the release process of `0.91.0`.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by kulbachcedric** [comment]
Hi @SvenO3 and @bossenti,
I just saw this issue and did the PyPi deployment once with [deep-river](https://github.com/online-ml/deep-river).
This workflow might help, whereby the `secrets.PYPI_API_TOKEN` needs to be set within the [settings](https://docs.github.com/en/actions/security-guides/encrypted-secrets) of the streampipes repository. 
Further, the path to the python libraries (python-wrapper and python-functional) needs to be changed.

```
# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
```
Hope this helps! 
Best
Cedric
