### ISSUE TITLE
Remove subnet from Docker Compose configuration

### ISSUE THREAD

**Issue by tenthe** [apache/streampipes#3450]
### Body

**Description:**  
The `spnet` network configuration includes a subnet definition that was originally added for Consul. Since Consul is no longer in use, this subnet can be removed to simplify the configuration.  

**Affected file(s):**  
- `docker-compose.yml`  

**Proposed fix:**  
Remove the following section from `docker-compose.yml`:  
```yaml
networks:
  spnet:
    driver: bridge
    ipam:
      config:
        - subnet: ${SP_SUBNET}
```  

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.
