### ISSUE TITLE
 Missing mapping in dev compose files for new docker-compose versions

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#667]
Some _docker-compose.dev.yml_ have no value after the service name.

This seems to be incompatible with docker-compose versions \> 1.x .

Errors are something like "services.xxx must be a mapping"

This error could be solved by adding a value.

What do you think about just adding a label to avoid this error?

With this extension docker-compose 2.x and 3.x can be used.

 

Example:

Old:
```

version: "3.4"
services:
  ui:

```

New:
```

version: "3.4"
services:
  ui:
    labels:
      org.apache.streampipes.dev.ui.service.description:
"Dev UI service"
 
```

Imported from Jira [STREAMPIPES-515](https://issues.apache.org/jira/browse/STREAMPIPES-515). Original Jira may contain additional context.
Reported by: obermeier.
